[project]
name = "vc"
version = "0.0.1"
dependencies = [
    "galois",
    "numpy",
    "pymerkle"
]

[project.optional-dependencies]
test = [
    "pytest"
]

[project.scripts]
vc = "vc.cli.main:main"
